name: Test

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**/*.yaml
      - autoload/**/*.vim
      - plugin/**/*.vim
      - scripts/**/*.py
      - scripts/**/*.sh
      - tests/**/*.vader

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/**/*.yaml
      - autoload/**/*.vim
      - plugin/**/*.vim
      - scripts/**/*.py
      - scripts/**/*.sh
      - tests/**/*.vader

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        id: cache-test-dependencies
        with:
          path: |
            /tmp/vim
            /home/runner/vim-v9.1.0774
            /home/runner/.vim
            /home/runner/vim
          key: ubuntu-latest_v9.1.0774

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: rhysd/action-setup-vim@v1.3.5
        if: steps.cache-test-dependencies.outputs.cache-hit != 'true'
        with:
          version: v9.1.0774
          configure-args: |
            --with-features=huge --enable-fail-if-missing --disable-nls

      - name: Update PATH with cached dependencies
        if: steps.cache-test-dependencies.outputs.cache-hit == 'true'
        run: |
          export PATH="/home/runner/vim-v9.1.0774/bin:$PATH"

      - name: Install Vader
        if: steps.cache-test-dependencies.outputs.cache-hit != 'true'
        run: |
          mkdir -vp ~/.vim/plugged
          pushd ~/.vim/plugged
          git clone https://github.com/junegunn/vader.vim.git
          popd

      - name: Test units
        run: |
          scripts/vader-run-tests.sh --test units --cicd > /dev/null

      # - name: Test mocks
      #   run: |
      #     scripts/vader-run-tests.sh --test mocks --cicd > /dev/null


##
# Attribution:
#
# - https://github.com/junegunn/vader.vim/?tab=readme-ov-file#github-actions
# - https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
